name: Version Bump and Release

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and build
        run: |
          npm run format:check
          npm run build

      - name: Install semantic-release
        run: |
          npm install -g semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/npm \
            @semantic-release/github \
            @semantic-release/git

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Push changes if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing and pushing"
            git add .
            git commit -m "chore: update version and changelog [skip ci]" || echo "No changes to commit"
            git push --follow-tags origin HEAD:${{ github.ref_name }}
          else
            echo "No changes detected, skipping commit"
            git push --follow-tags origin HEAD:${{ github.ref_name }}
          fi
